# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener:  true
    serializer:
        serialize_null: true
    format_listener: 
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }

sensio_framework_extra:
    request : { converters: true}
